name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTING: "true"
      OPENAI_API_KEY: "fake-api-key"
      MONGO_URI: "mongodb://localhost:27017"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/ -v --cov=app

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: success()

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Install Elastic Beanstalk CLI
      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          export PATH=$PATH:~/.local/bin

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 042077470246.dkr.ecr.ap-south-1.amazonaws.com

      # Step 5: Build and tag the Docker image
      - name: Build Docker image
        run: |
          docker build -t adaptive-learning-api .
          docker tag adaptive-learning-api:latest 042077470246.dkr.ecr.ap-south-1.amazonaws.com/adaptive-learning-api:latest

      # Step 6: Push the Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push 042077470246.dkr.ecr.ap-south-1.amazonaws.com/adaptive-learning-api:latest

      # Step 7: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        env:
          AWS_REGION: ap-south-1
        run: |
          eb init -p docker adaptive-learning-api --region $AWS_REGION
          eb deploy
