name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create mock .env file
      run: |
        echo "OPENAI_API_KEY=fake-api-key" > .env
        echo "MONGO_URI=mongodb://localhost:27017" >> .env

    - name: Run tests
      run: |
        pytest tests/ -v --cov=app

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: success()
